# Generated by Django 4.0.4 on 2022-05-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackholders', '0001_initial'),
        ('course', '0002_course_student_alter_course_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stackholders.profile'),
        ),
    ]
