# Generated by Django 4.0.4 on 2022-05-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackholders', '0001_initial'),
        ('course', '0002_course_created_time_alter_assignment_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submisstion',
            new_name='Submission',
        ),
    ]
