# Generated by Django 4.0.4 on 2022-05-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackholders', '0001_initial'),
        ('course', '0003_alter_course_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='stu', to='stackholders.profile'),
        ),
    ]
